# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=${MONGO_DB_URL}
spring.data.mongodb.database=edurag

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Gemini API
gemini.api.key=${API_KEY1}

gemini.api.base-url=https://generativelanguage.googleapis.com/v1
gemini.model.chat=gemini-2.0-flash
gemini.model.embedding=gemini-embedding-001
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile
# Chunking Config
chunking.size=500
chunking.overlap=100

# Upload directory
upload.dir=uploads/
